// <auto-generated />
namespace University_Manager_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class your_migr_name2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(your_migr_name2));
        
        string IMigrationMetadata.Id
        {
            get { return "202102221451491_your_migr_name2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
